// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"collabotask/internal/usecase/common"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBoardAccessChecker creates a new instance of MockBoardAccessChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBoardAccessChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBoardAccessChecker {
	mock := &MockBoardAccessChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBoardAccessChecker is an autogenerated mock type for the BoardAccessChecker type
type MockBoardAccessChecker struct {
	mock.Mock
}

type MockBoardAccessChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBoardAccessChecker) EXPECT() *MockBoardAccessChecker_Expecter {
	return &MockBoardAccessChecker_Expecter{mock: &_m.Mock}
}

// CheckMetadataAccess provides a mock function for the type MockBoardAccessChecker
func (_mock *MockBoardAccessChecker) CheckMetadataAccess(ctx context.Context, boardID uuid.UUID, requesterID uuid.UUID) (*common.BoardAccess, error) {
	ret := _mock.Called(ctx, boardID, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for CheckMetadataAccess")
	}

	var r0 *common.BoardAccess
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*common.BoardAccess, error)); ok {
		return returnFunc(ctx, boardID, requesterID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *common.BoardAccess); ok {
		r0 = returnFunc(ctx, boardID, requesterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.BoardAccess)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, boardID, requesterID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoardAccessChecker_CheckMetadataAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckMetadataAccess'
type MockBoardAccessChecker_CheckMetadataAccess_Call struct {
	*mock.Call
}

// CheckMetadataAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - boardID uuid.UUID
//   - requesterID uuid.UUID
func (_e *MockBoardAccessChecker_Expecter) CheckMetadataAccess(ctx any, boardID any, requesterID any) *MockBoardAccessChecker_CheckMetadataAccess_Call {
	return &MockBoardAccessChecker_CheckMetadataAccess_Call{Call: _e.mock.On("CheckMetadataAccess", ctx, boardID, requesterID)}
}

func (_c *MockBoardAccessChecker_CheckMetadataAccess_Call) Run(run func(ctx context.Context, boardID uuid.UUID, requesterID uuid.UUID)) *MockBoardAccessChecker_CheckMetadataAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBoardAccessChecker_CheckMetadataAccess_Call) Return(boardAccess *common.BoardAccess, err error) *MockBoardAccessChecker_CheckMetadataAccess_Call {
	_c.Call.Return(boardAccess, err)
	return _c
}

func (_c *MockBoardAccessChecker_CheckMetadataAccess_Call) RunAndReturn(run func(ctx context.Context, boardID uuid.UUID, requesterID uuid.UUID) (*common.BoardAccess, error)) *MockBoardAccessChecker_CheckMetadataAccess_Call {
	_c.Call.Return(run)
	return _c
}

// CheckMutateAccess provides a mock function for the type MockBoardAccessChecker
func (_mock *MockBoardAccessChecker) CheckMutateAccess(ctx context.Context, boardID uuid.UUID, requesterID uuid.UUID) (*common.BoardAccess, error) {
	ret := _mock.Called(ctx, boardID, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for CheckMutateAccess")
	}

	var r0 *common.BoardAccess
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*common.BoardAccess, error)); ok {
		return returnFunc(ctx, boardID, requesterID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *common.BoardAccess); ok {
		r0 = returnFunc(ctx, boardID, requesterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.BoardAccess)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, boardID, requesterID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoardAccessChecker_CheckMutateAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckMutateAccess'
type MockBoardAccessChecker_CheckMutateAccess_Call struct {
	*mock.Call
}

// CheckMutateAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - boardID uuid.UUID
//   - requesterID uuid.UUID
func (_e *MockBoardAccessChecker_Expecter) CheckMutateAccess(ctx any, boardID any, requesterID any) *MockBoardAccessChecker_CheckMutateAccess_Call {
	return &MockBoardAccessChecker_CheckMutateAccess_Call{Call: _e.mock.On("CheckMutateAccess", ctx, boardID, requesterID)}
}

func (_c *MockBoardAccessChecker_CheckMutateAccess_Call) Run(run func(ctx context.Context, boardID uuid.UUID, requesterID uuid.UUID)) *MockBoardAccessChecker_CheckMutateAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBoardAccessChecker_CheckMutateAccess_Call) Return(boardAccess *common.BoardAccess, err error) *MockBoardAccessChecker_CheckMutateAccess_Call {
	_c.Call.Return(boardAccess, err)
	return _c
}

func (_c *MockBoardAccessChecker_CheckMutateAccess_Call) RunAndReturn(run func(ctx context.Context, boardID uuid.UUID, requesterID uuid.UUID) (*common.BoardAccess, error)) *MockBoardAccessChecker_CheckMutateAccess_Call {
	_c.Call.Return(run)
	return _c
}

// CheckViewAccess provides a mock function for the type MockBoardAccessChecker
func (_mock *MockBoardAccessChecker) CheckViewAccess(ctx context.Context, boardID uuid.UUID, requesterID uuid.UUID) (*common.BoardAccess, error) {
	ret := _mock.Called(ctx, boardID, requesterID)

	if len(ret) == 0 {
		panic("no return value specified for CheckViewAccess")
	}

	var r0 *common.BoardAccess
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*common.BoardAccess, error)); ok {
		return returnFunc(ctx, boardID, requesterID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *common.BoardAccess); ok {
		r0 = returnFunc(ctx, boardID, requesterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.BoardAccess)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, boardID, requesterID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoardAccessChecker_CheckViewAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckViewAccess'
type MockBoardAccessChecker_CheckViewAccess_Call struct {
	*mock.Call
}

// CheckViewAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - boardID uuid.UUID
//   - requesterID uuid.UUID
func (_e *MockBoardAccessChecker_Expecter) CheckViewAccess(ctx any, boardID any, requesterID any) *MockBoardAccessChecker_CheckViewAccess_Call {
	return &MockBoardAccessChecker_CheckViewAccess_Call{Call: _e.mock.On("CheckViewAccess", ctx, boardID, requesterID)}
}

func (_c *MockBoardAccessChecker_CheckViewAccess_Call) Run(run func(ctx context.Context, boardID uuid.UUID, requesterID uuid.UUID)) *MockBoardAccessChecker_CheckViewAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBoardAccessChecker_CheckViewAccess_Call) Return(boardAccess *common.BoardAccess, err error) *MockBoardAccessChecker_CheckViewAccess_Call {
	_c.Call.Return(boardAccess, err)
	return _c
}

func (_c *MockBoardAccessChecker_CheckViewAccess_Call) RunAndReturn(run func(ctx context.Context, boardID uuid.UUID, requesterID uuid.UUID) (*common.BoardAccess, error)) *MockBoardAccessChecker_CheckViewAccess_Call {
	_c.Call.Return(run)
	return _c
}
